# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

niah_single:
  task: niah
  args:
    type_haystack: book
    type_needle_k: words
    type_needle_v: numbers
    num_needle_k: 1
    num_needle_v: 1
    num_needle_q: 1

niah_multikey:
  task: niah
  args:
    type_haystack: book
    type_needle_k: words
    type_needle_v: numbers
    num_needle_k: 4
    num_needle_v: 1
    num_needle_q: 1

niah_multivalue:
  task: niah
  args:
    type_haystack: book
    type_needle_k: words
    type_needle_v: numbers
    num_needle_k: 1
    num_needle_v: 4
    num_needle_q: 1

niah_multiquery:
  task: niah
  args:
    type_haystack: book
    type_needle_k: words
    type_needle_v: numbers
    num_needle_k: 1
    num_needle_v: 1
    num_needle_q: 2

niah_none:
  task: niah
  args:
    type_haystack: book
    type_needle_k: words
    type_needle_v: numbers
    relevant_needle: 0 
    num_needle_k: 4
    num_needle_v: 1
    num_needle_q: 1

cwe:
  task: common_words_extraction
  args:
    freq_cw: 20
    freq_ucw: 10
    num_cw: 10

cwe_easy:
  task: common_words_extraction
  args:
    freq_cw: 30
    freq_ucw: 3
    num_cw: 10    
    
fwe:
  task: freq_words_extraction
  args:
    alpha: 2.0
